# Generated by Django 5.0.14 on 2026-07-24 14:28

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price_minor', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('sale_start', models.DateTimeField(blank=True, null=True)),
                ('sale_end', models.DateTimeField(blank=True, null=True)),
                ('max_per_order', models.PositiveIntegerField(default=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_types', to='events.event')),
            ],
            options={
                'db_table': 'ticketing_ticket_type',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['event', 'price_minor'], name='tickettype_event_price_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(check=models.Q(('sold__gte', 0), ('reserved__gte', 0), ('quantity__gte', django.db.models.expressions.CombinedExpression(models.F('sold'), '+', models.F('reserved')))), name='ticket_type_no_oversell'),
        ),
    ]
