# Generated by Django 5.0.14 on 2026-08-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_savedevent_savedevent_saved_event_user_event_uniq'),
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='early_bird_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='early_bird_price_minor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='early_bird_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(check=models.Q(('early_bird_price_minor__isnull', True), ('early_bird_price_minor__lte', models.F('price_minor')), _connector='OR'), name='ticket_type_early_bird_not_above_price'),
        ),
    ]
