# Generated by Django 5.0.14 on 2026-08-03 15:31, then edited: the data copy
# runs in the SAME migration as the schema change, so no deployed state ever
# has early-bird columns without phases or phases without the columns' data.
"""Named sale phases replace the anonymous early-bird columns.

Every tier with an early bird becomes a one-phase schedule: the discount was
always "the first phase" in all but name, so the copy is
`SalePhase(name='Early bird', position=0)` carrying the same price, deadline
and (cumulative) seat threshold. The three columns and their CHECK constraint
then go — the price-at-or-below-face rule now lives in the service across the
whole schedule (a cross-row rule a single-table CHECK can't express).

The data copy is reversible-safe in this repo's usual style: reversing
restores each tier's position-0 phase back into the early-bird columns (later
phases have no columns to return to and are dropped with the table — the
reverse recovers what the old schema could represent, no more).
"""

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_early_bird_to_phases(apps, schema_editor):
    TicketType = apps.get_model("ticketing", "TicketType")
    SalePhase = apps.get_model("ticketing", "SalePhase")

    SalePhase.objects.bulk_create(
        [
            SalePhase(
                ticket_type_id=tt.id,
                name="Early bird",
                price_minor=tt.early_bird_price_minor,
                ends_at=tt.early_bird_ends_at,
                quantity=tt.early_bird_quantity,
                position=0,
            )
            for tt in TicketType.objects.filter(early_bird_price_minor__isnull=False)
            .only("id", "early_bird_price_minor", "early_bird_ends_at", "early_bird_quantity")
            .iterator()
        ]
    )


def copy_phases_back_to_early_bird(apps, schema_editor):
    """Best-effort reverse: the position-0 phase becomes the early bird again.
    Runs after the reversed RemoveFields re-add the (null) columns and before
    the table is dropped."""
    TicketType = apps.get_model("ticketing", "TicketType")
    SalePhase = apps.get_model("ticketing", "SalePhase")

    for phase in SalePhase.objects.filter(position=0).iterator():
        TicketType.objects.filter(pk=phase.ticket_type_id).update(
            early_bird_price_minor=phase.price_minor,
            early_bird_ends_at=phase.ends_at,
            early_bird_quantity=phase.quantity,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_tickettype_early_bird_ends_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('price_minor', models.PositiveIntegerField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'ticketing_sale_phase',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='salephase',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='ticketing.tickettype'),
        ),
        migrations.AddConstraint(
            model_name='salephase',
            constraint=models.UniqueConstraint(fields=('ticket_type', 'position'), name='sale_phase_position_uniq'),
        ),
        # The copy runs while BOTH shapes exist: the phases table is up, the
        # early-bird columns are still readable.
        migrations.RunPython(copy_early_bird_to_phases, copy_phases_back_to_early_bird),
        migrations.RemoveConstraint(
            model_name='tickettype',
            name='ticket_type_early_bird_not_above_price',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='early_bird_ends_at',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='early_bird_price_minor',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='early_bird_quantity',
        ),
    ]
