# Generated by Django 5.0.14 on 2026-08-08 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventslot_eventslot_event_slot_unique_start_label'),
        ('ticketing', '0003_sale_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_types', to='events.eventslot'),
        ),
    ]
