# Generated by Django 5.0.14 on 2026-08-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_tickettype_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='perks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
