# Generated by Django 5.1.15 on 2026-09-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_tickettype_description_tickettype_perks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='group_bands',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
