# Generated by Django 5.1.15 on 2026-09-15 18:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticketing", "0006_tickettype_group_bands"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingFeatureChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[("early_bird", "Early bird"), ("group_offers", "Group offers")],
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField()),
                ("changed_at", models.DateTimeField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("edited", "Edited"),
                            ("baseline", "Baseline"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_changes",
                        to="ticketing.tickettype",
                    ),
                ),
            ],
            options={
                "db_table": "ticketing_pricing_feature_change",
                "indexes": [
                    models.Index(
                        fields=["ticket_type", "feature", "changed_at"],
                        name="feature_change_tier_time_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TicketPriceChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("price_minor", models.PositiveIntegerField()),
                ("changed_at", models.DateTimeField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("edited", "Edited"),
                            ("baseline", "Baseline"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_changes",
                        to="ticketing.tickettype",
                    ),
                ),
            ],
            options={
                "db_table": "ticketing_price_change",
                "indexes": [
                    models.Index(
                        fields=["ticket_type", "changed_at"], name="price_change_tier_time_idx"
                    )
                ],
            },
        ),
    ]
