# Generated by Django 5.0.14 on 2026-07-24 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('welcome', 'Welcome email'), ('ticket_delivery', 'Ticket delivery email'), ('booking_confirmation_sms', 'Booking confirmation SMS'), ('refund_confirmation', 'Refund confirmation email'), ('refund_confirmation_sms', 'Refund confirmation SMS'), ('otp', 'OTP SMS'), ('event_reminder', 'Event reminder email')], max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=16)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications_notification_log',
                'indexes': [models.Index(fields=['status', 'created_at'], name='notiflog_status_created_idx')],
            },
        ),
    ]
