# Generated by Django 5.0.14 on 2026-07-29 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationlog_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='context_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Web Push')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('welcome', 'Welcome email'), ('ticket_delivery', 'Ticket delivery email'), ('booking_confirmation_sms', 'Booking confirmation SMS'), ('refund_confirmation', 'Refund confirmation email'), ('refund_confirmation_sms', 'Refund confirmation SMS'), ('otp', 'OTP SMS'), ('event_reminder', 'Event reminder email'), ('event_reminder_push', 'Event reminder push'), ('payout_released', 'Payout released email')], max_length=64),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField()),
                ('endpoint_hash', models.CharField(max_length=64, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_push_subscription',
                'indexes': [models.Index(fields=['user', 'created_at'], name='pushsub_user_created_idx')],
            },
        ),
    ]
