# Generated by Django 5.0.14 on 2026-07-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationlog_context_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('welcome', 'Welcome email'), ('ticket_delivery', 'Ticket delivery email'), ('booking_confirmation_sms', 'Booking confirmation SMS'), ('refund_confirmation', 'Refund confirmation email'), ('refund_confirmation_sms', 'Refund confirmation SMS'), ('otp', 'OTP SMS'), ('email_verification', 'Email verification code'), ('event_reminder', 'Event reminder email'), ('event_reminder_push', 'Event reminder push'), ('payout_released', 'Payout released email')], max_length=64),
        ),
    ]
