# Generated by Django 5.0.14 on 2026-07-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationlog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='html_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
