# Generated by Django 5.0.14 on 2026-07-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationlog_html_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='attachments_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('welcome', 'Welcome email'), ('ticket_delivery', 'Ticket delivery email'), ('booking_confirmation_sms', 'Booking confirmation SMS'), ('refund_confirmation', 'Refund confirmation email'), ('refund_confirmation_sms', 'Refund confirmation SMS'), ('otp', 'OTP SMS'), ('email_verification', 'Email verification code'), ('event_reminder', 'Event reminder email'), ('event_reminder_push', 'Event reminder push'), ('booking_confirmed_push', 'Booking confirmed push'), ('payout_released', 'Payout released email')], max_length=64),
        ),
    ]
