# Generated by Django 5.0.14 on 2026-08-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationlog_attachments_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('welcome', 'Welcome email'), ('ticket_delivery', 'Ticket delivery email'), ('booking_confirmation_sms', 'Booking confirmation SMS'), ('refund_confirmation', 'Refund confirmation email'), ('refund_confirmation_sms', 'Refund confirmation SMS'), ('otp', 'OTP SMS'), ('email_verification', 'Email verification code'), ('event_reminder', 'Event reminder email'), ('event_reminder_push', 'Event reminder push'), ('booking_confirmed_push', 'Booking confirmed push'), ('payout_released', 'Payout released email'), ('admin_event_review', 'Admin: event awaiting review'), ('admin_org_verification', 'Admin: organization awaiting verification'), ('admin_performer_review', 'Admin: performer awaiting review')], max_length=64),
        ),
    ]
