# Generated by Django 5.0.14 on 2026-08-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notificationlog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('welcome', 'Welcome email'), ('ticket_delivery', 'Ticket delivery email'), ('attendee_ticket', 'Attendee ticket email'), ('booking_confirmation_sms', 'Booking confirmation SMS'), ('booking_receipt_shared', 'Shared booking receipt'), ('refund_confirmation', 'Refund confirmation email'), ('event_cancelled_attendee', 'Event cancelled (attendee)'), ('event_deleted_organizer', 'Event removed (organizer)'), ('refund_request_received', 'Refund request received (organizer)'), ('refund_request_approved', 'Refund request approved'), ('refund_request_rejected', 'Refund request rejected'), ('refund_confirmation_sms', 'Refund confirmation SMS'), ('otp', 'OTP SMS'), ('email_verification', 'Email verification code'), ('event_reminder', 'Event reminder email'), ('event_reminder_push', 'Event reminder push'), ('booking_confirmed_push', 'Booking confirmed push'), ('payout_released', 'Payout released email'), ('admin_event_review', 'Admin: event awaiting review'), ('admin_org_verification', 'Admin: organization awaiting verification'), ('admin_performer_review', 'Admin: performer awaiting review'), ('admin_hire_enquiry', 'Admin: hire enquiry received'), ('hire_enquiry_received', 'Hire enquiry received')], max_length=64),
        ),
    ]
