import { NextResponse } from 'next/server';
import { API_BASE_URL } from '@/lib/api/config';

/**
 * The push service worker, served from `/sw.js`.
 *
 * ── WHY A ROUTE HANDLER AND NOT `public/sw.js` ────────────────────────────
 *
 * The worker has to call the API, and a file in `public/` is served verbatim
 * — there is no build step that could substitute the API origin into it. A
 * service worker also cannot read `process.env`, and it outlives every page,
 * so it cannot rely on a page having told it where the API lives either.
 *
 * Serving it from a route handler means the origin is injected at request
 * time from the same `API_BASE_URL` the rest of the app uses, so there is one
 * source of truth rather than a second copy that drifts.
 *
 * Path matters: a worker registered from a subdirectory can only receive
 * pushes for that subdirectory. `/sw.js` is at the root, so its scope is the
 * whole origin.
 *
 * ── WHAT IT DELIBERATELY DOES NOT DO ──────────────────────────────────────
 *
 * No fetch interception, no response caching, no offline shell. A service
 * worker that quietly serves stale HTML is how a ticketing site shows a
 * sold-out event as available. Offline support is a decision worth taking on
 * purpose, not one to acquire as a side effect of wanting notifications.
 */
export const dynamic = 'force-dynamic';

export function GET() {
  const body = `// Generated by app/sw.js/route.ts — do not edit a copy of this.
const API_BASE = ${JSON.stringify(API_BASE_URL)};

// Take over immediately rather than waiting for every tab to close. A push
// subscription belongs to the registration, so an old worker lingering after a
// deploy means pushes keep being handled by code we already replaced.
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (event) => event.waitUntil(self.clients.claim()));

self.addEventListener('push', (event) => {
  // A push with no payload is legal — some services send one just to wake the
  // worker. Showing nothing beats showing "undefined".
  let data = {};
  try {
    data = event.data ? event.data.json() : {};
  } catch {
    data = {};
  }
  if (!data.title && !data.body) return;

  event.waitUntil(
    self.registration.showNotification(data.title || 'Curatix', {
      body: data.body || '',
      icon: '/favicon.svg',
      badge: '/favicon.svg',
      // The server sends the notification's dedupe key as the tag, so a
      // redelivery REPLACES the visible notification rather than stacking a
      // second identical one. Two copies of one reminder is how somebody
      // decides to turn notifications off.
      tag: data.tag || undefined,
      data: { url: data.url || '/' },
      requireInteraction: false,
    }),
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const target = (event.notification.data && event.notification.data.url) || '/';

  event.waitUntil(
    (async () => {
      const windows = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
      // Focus a tab already on this site rather than opening a third copy of
      // it. Someone tapping a reminder with the site already open should land
      // in the window they have.
      for (const client of windows) {
        if (client.url.startsWith(self.location.origin) && 'focus' in client) {
          await client.focus();
          if ('navigate' in client && target !== '/') {
            try {
              await client.navigate(target);
            } catch {
              // A client that refuses navigation. Focusing already happened,
              // which is most of what was wanted.
            }
          }
          return;
        }
      }
      await self.clients.openWindow(target);
    })(),
  );
});

// A push service may rotate a subscription with no page open. The old endpoint
// stops working at that moment, and nothing on the client would notice until
// the next visit — so the worker re-subscribes and tells the server itself.
//
// It has no access token (a service worker cannot read one), so it sends the
// NEW subscription along with the OLD endpoint. Knowing the old endpoint IS
// the evidence that this is the same subscription; the server rotates the row
// it already has and can neither create one nor change its owner.
self.addEventListener('pushsubscriptionchange', (event) => {
  event.waitUntil(
    (async () => {
      const oldEndpoint = event.oldSubscription && event.oldSubscription.endpoint;
      const key =
        (event.oldSubscription && event.oldSubscription.options.applicationServerKey) || null;
      if (!oldEndpoint || !key) return;

      let fresh;
      try {
        fresh = await self.registration.pushManager.subscribe({
          userVisibleOnly: true,
          applicationServerKey: key,
        });
      } catch {
        return; // The page re-subscribes on the next visit; that is the backstop.
      }

      const json = fresh.toJSON();
      await fetch(API_BASE + '/api/v1/push/rotate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          old_endpoint: oldEndpoint,
          endpoint: json.endpoint,
          p256dh: json.keys.p256dh,
          auth: json.keys.auth,
        }),
      }).catch(() => {});
    })(),
  );
});
`;

  return new NextResponse(body, {
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      // Never cached. A stale worker is one that keeps handling pushes with
      // code from a previous deploy, and browsers already re-check `/sw.js`
      // aggressively — fighting that gains nothing and risks a lot.
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Service-Worker-Allowed': '/',
    },
  });
}
