# Generated by Django 5.0.14 on 2026-07-24 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('gate', models.CharField(blank=True, default='', max_length=100)),
                ('result', models.CharField(choices=[('allowed', 'Allowed'), ('denied_already_used', 'Denied — already used'), ('denied_invalid', 'Denied — invalid token'), ('denied_wrong_event', 'Denied — wrong event'), ('denied_not_active', 'Denied — ticket not active'), ('denied_out_of_window', 'Denied — outside scan window')], max_length=32)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_logs', to='events.event')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_logs', to='booking.ticket')),
            ],
            options={
                'db_table': 'checkin_scan_log',
                'indexes': [models.Index(fields=['event', 'scanned_at'], name='scanlog_event_scanned_idx'), models.Index(fields=['ticket'], name='scanlog_ticket_idx')],
            },
        ),
    ]
