# Generated by Django 5.0.14 on 2026-07-24 05:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models

# The search_vector tsvector is maintained entirely in the database by a
# trigger, so it's always consistent with title/venue/city/description with
# zero application code (and can never drift if a row is written by some path
# that forgets to update it). Weights rank a title hit (A) above a
# venue/city hit (B) above a description hit (C). The INSERT trigger always
# fires; the UPDATE trigger fires only when one of the source columns is in
# the UPDATE's SET list (BEFORE UPDATE OF ...), so a status-only change
# (publish) or a poster-url change doesn't needlessly recompute the vector.
_TSV_FORWARD = r"""
CREATE FUNCTION events_event_tsv_refresh() RETURNS trigger AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(NEW.venue, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(NEW.city, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(NEW.description, '')), 'C');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER events_event_tsv_insert
    BEFORE INSERT ON events_event
    FOR EACH ROW EXECUTE FUNCTION events_event_tsv_refresh();

CREATE TRIGGER events_event_tsv_update
    BEFORE UPDATE OF title, venue, city, description ON events_event
    FOR EACH ROW EXECUTE FUNCTION events_event_tsv_refresh();

-- Backfill any existing rows (a no-op on this fresh table, but keeps the
-- migration correct if it's ever applied to already-populated data).
UPDATE events_event SET search_vector =
    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(venue, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(city, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'C');
"""

_TSV_REVERSE = r"""
DROP TRIGGER IF EXISTS events_event_tsv_update ON events_event;
DROP TRIGGER IF EXISTS events_event_tsv_insert ON events_event;
DROP FUNCTION IF EXISTS events_event_tsv_refresh();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('venue', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('paused', 'Paused'), ('finished', 'Finished'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('poster_url', models.CharField(blank=True, default='', max_length=500)),
                ('from_price_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('tickets_available', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='organizations.organization')),
            ],
            options={
                'db_table': 'events_event',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['status', 'starts_at'], name='event_status_starts_idx'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['status', 'city', 'starts_at'], name='event_status_city_starts_idx'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'created_at'], name='event_org_created_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='event_search_vector_gin')],
            },
        ),
        migrations.RunSQL(sql=_TSV_FORWARD, reverse_sql=_TSV_REVERSE),
    ]
