# Generated by Django 5.0.14 on 2026-07-28 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_moderated_at_event_moderated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accessibility_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='age_restriction',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_description',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='EventFaq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='events.event')),
            ],
            options={
                'db_table': 'events_event_faq',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True), ('is_published', True)), fields=['event', 'position'], name='event_faq_ordered_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('hero', 'Hero banner'), ('gallery', 'Gallery image'), ('thumbnail', 'Thumbnail'), ('mobile', 'Mobile banner'), ('video', 'Hero video')], default='gallery', max_length=20)),
                ('url', models.CharField(max_length=500)),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='events.event')),
            ],
            options={
                'db_table': 'events_event_media',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True), ('is_visible', True)), fields=['event', 'kind', 'position'], name='event_media_ordered_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventTimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('doors', 'Doors open'), ('opening', 'Opening act'), ('session', 'Session'), ('intermission', 'Intermission'), ('main', 'Main show'), ('after_party', 'After party'), ('closing', 'Closing')], default='main', max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='events.event')),
            ],
            options={
                'db_table': 'events_event_timeline',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['event', 'position'], name='event_timeline_ordered_idx')],
            },
        ),
    ]
