# Generated by Django 5.0.14 on 2026-08-08 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_savedevent_savedevent_saved_event_user_event_uniq'),
        ('organizations', '0002_organizationfollow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('concerts', 'Concerts'), ('comedy', 'Comedy'), ('workshops', 'Workshops'), ('sports', 'Sports'), ('festivals', 'Festivals'), ('nightlife', 'Nightlife'), ('food-drink', 'Food & Drink'), ('tech', 'Tech'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['status', 'category', 'starts_at'], name='event_status_category_idx'),
        ),
    ]
