# Generated by Django 5.0.14 on 2026-08-08 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_category_event_event_status_category_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='events.event')),
            ],
            options={
                'db_table': 'events_event_slot',
                'indexes': [models.Index(fields=['event', 'position', 'starts_at'], name='event_slot_order_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventslot',
            constraint=models.UniqueConstraint(fields=('event', 'starts_at', 'label'), name='event_slot_unique_start_label'),
        ),
    ]
