# Generated by Django 5.0.14 on 2026-08-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventslot_eventslot_event_slot_unique_start_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='policies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
