# Generated by Django 5.0.14 on 2026-08-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
