# Generated by Django 5.1.15 on 2026-09-02 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_backfill_event_slug'),
        ('organizations', '0002_organizationfollow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['status', 'organization', 'starts_at'], name='event_status_org_starts_idx'),
        ),
    ]
