# Generated by Django 5.1.15 on 2026-09-02 18:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_status_org_starts_idx'),
        ('organizations', '0002_organizationfollow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, default='', max_length=80)),
                ('details', models.TextField(blank=True, default='')),
                ('photo_url', models.CharField(blank=True, default='', max_length=500)),
                ('photo_alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crew_members', to='organizations.organization')),
            ],
            options={
                'db_table': 'crew_member',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EventCrew',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billed_as', models.CharField(blank=True, default='', max_length=80)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='events.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appearances', to='events.crewmember')),
            ],
            options={
                'db_table': 'event_crew',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='crewmember',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'name', 'id'], name='crew_member_org_name_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcrew',
            index=models.Index(fields=['event', 'position', 'id'], name='event_crew_event_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventcrew',
            constraint=models.UniqueConstraint(fields=('event', 'member'), name='event_crew_unique_member'),
        ),
    ]
