# Generated by Django 5.1.15 on 2026-09-05 20:27

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_crew_members'),
        ('organizations', '0002_organizationfollow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('music-jam', 'Music jam'), ('concert', 'Concert'), ('gig', 'Gig'), ('open-mic', 'Open mic'), ('dj-night', 'DJ night'), ('club-night', 'Club night'), ('comedy-show', 'Comedy show'), ('theatre', 'Theatre'), ('film-screening', 'Film screening'), ('storytelling', 'Storytelling'), ('art-workshop', 'Art workshop'), ('craft-workshop', 'Craft workshop'), ('pottery', 'Pottery'), ('photography-walk', 'Photography walk'), ('cooking-class', 'Cooking class'), ('tasting', 'Tasting'), ('food-festival', 'Food festival'), ('supper-club', 'Supper club'), ('hackathon', 'Hackathon'), ('tech-talk', 'Tech talk'), ('conference', 'Conference'), ('panel-discussion', 'Panel discussion'), ('meetup', 'Meetup'), ('book-club', 'Book club'), ('discussion-circle', 'Discussion circle'), ('language-exchange', 'Language exchange'), ('singles-social', 'Singles social'), ('speed-dating', 'Speed dating'), ('board-games', 'Board games'), ('quiz-night', 'Quiz night'), ('karaoke', 'Karaoke'), ('city-walk', 'City walk'), ('heritage-walk', 'Heritage walk'), ('trek', 'Trek / hike'), ('camping', 'Camping'), ('cycling-ride', 'Cycling ride'), ('run', 'Run'), ('farm-visit', 'Farm visit'), ('yoga', 'Yoga'), ('fitness-class', 'Fitness class'), ('wellness-session', 'Wellness session'), ('retreat', 'Retreat'), ('sports-tournament', 'Sports tournament'), ('esports', 'Esports'), ('exhibition', 'Exhibition'), ('flea-market', 'Flea market'), ('pop-up', 'Pop-up'), ('kids-workshop', 'Kids workshop')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='guidelines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='highlights_excluded',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='highlights_included',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['status', 'event_type', 'starts_at'], name='event_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='event_tags_gin'),
        ),
    ]
