# Generated by Django 5.1.15 on 2026-09-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_taxonomy_and_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmedia',
            name='is_vertical',
            field=models.BooleanField(default=False),
        ),
    ]
