# Generated by Django 5.1.15 on 2026-09-06 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_media_is_vertical'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.CharField(max_length=200)),
                ('help_text', models.CharField(blank=True, default='', max_length=200)),
                ('kind', models.CharField(choices=[('short_text', 'Short answer'), ('long_text', 'Long answer'), ('choice', 'Choose one'), ('boolean', 'Yes or no')], default='short_text', max_length=20)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.event')),
            ],
            options={
                'db_table': 'events_event_question',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['event', 'position'], name='event_question_ordered_idx')],
            },
        ),
    ]
