# Generated by Django 5.1.15 on 2026-09-06 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_attendee_questionnaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventWaitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlisted_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_event_waitlist',
                'indexes': [models.Index(condition=models.Q(('notified_at__isnull', True)), fields=['event', 'created_at', 'id'], name='event_waitlist_pending'), models.Index(fields=['user', '-created_at'], name='event_waitlist_user_recent')],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='event_waitlist_unique_member')],
            },
        ),
    ]
