# Generated by Django 5.1.15 on 2026-09-06 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_event_ends_after_starts'),
        ('organizations', '0002_organizationfollow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60)),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('image_alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_categories', to='organizations.organization')),
            ],
            options={
                'db_table': 'events_organizer_category',
                'ordering': ('label', 'id'),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='custom_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.organizercategory'),
        ),
        migrations.AddIndex(
            model_name='organizercategory',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'label', 'id'], name='organizer_category_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizercategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'slug'), name='organizer_category_unique_slug'),
        ),
    ]
