# Generated by Django 5.1.15 on 2026-09-15 18:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0020_organizercategory_event_custom_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventEngagementDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("views", models.PositiveIntegerField(default=0)),
                ("feed_views", models.PositiveIntegerField(default=0)),
                ("located_views", models.PositiveIntegerField(default=0)),
                ("local_views", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_days",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "events_engagement_day",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "date"), name="event_engagement_day_uniq"
                    )
                ],
            },
        ),
    ]
