# Generated by Django 5.0.14 on 2026-07-28 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event_moderated_at_event_moderated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('icon', models.CharField(blank=True, default='', max_length=60)),
                ('search_term', models.CharField(blank=True, default='', max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cms_category',
                'indexes': [models.Index(condition=models.Q(('archived_at__isnull', True), ('is_visible', True)), fields=['position'], name='cms_category_visible_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('hero_headline', models.CharField(blank=True, default='', max_length=80)),
                ('hero_description', models.CharField(blank=True, default='', max_length=180)),
                ('hero_primary_cta', models.CharField(blank=True, default='', max_length=40)),
                ('hero_secondary_cta', models.CharField(blank=True, default='', max_length=40)),
                ('search_placeholder', models.CharField(blank=True, default='', max_length=80)),
                ('ribbon_text', models.CharField(blank=True, default='', max_length=120)),
                ('ribbon_enabled', models.BooleanField(default=False)),
                ('trust_badges', models.JSONField(blank=True, default=list)),
                ('footer_note', models.CharField(blank=True, default='', max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_homepage_content',
            },
        ),
        migrations.CreateModel(
            name='FeaturedEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection', models.CharField(choices=[('featured', 'Featured'), ('trending', 'Trending'), ('editors_pick', "Editor's pick"), ('recommended', 'Recommended'), ('new', 'New')], max_length=32)),
                ('position', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entries', to='events.event')),
            ],
            options={
                'db_table': 'cms_featured_entry',
                'indexes': [models.Index(fields=['collection', 'position'], name='cms_featured_collection_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='featuredentry',
            constraint=models.UniqueConstraint(fields=('collection', 'event'), name='cms_featured_unique_per_collection'),
        ),
    ]
