# Generated by Django 5.0.14 on 2026-07-30 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_seed_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cms_featured_city',
                'ordering': ['position', 'name'],
                'indexes': [models.Index(condition=models.Q(('is_visible', True)), fields=['position'], name='cms_city_visible_pos')],
            },
        ),
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=60)),
                ('query', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cms_popular_search',
                'ordering': ['position', 'label'],
                'indexes': [models.Index(condition=models.Q(('is_visible', True)), fields=['position'], name='cms_popular_visible_pos')],
            },
        ),
        migrations.AddConstraint(
            model_name='popularsearch',
            constraint=models.UniqueConstraint(fields=('label',), name='cms_popular_search_label_uniq'),
        ),
    ]
