# Generated by Django 5.1.15 on 2026-09-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_seed_discovery_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
