# Generated by Django 5.0.14 on 2026-07-29 10:07

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=120)),
                ('performer_type', models.CharField(choices=[('band', 'Band'), ('singer', 'Singer'), ('dj', 'DJ'), ('instrumentalist', 'Instrumentalist'), ('anchor', 'Anchor / MC'), ('comedian', 'Stand-up comedian'), ('dance_crew', 'Dance crew'), ('magician', 'Magician'), ('other', 'Other')], max_length=20)),
                ('tagline', models.CharField(blank=True, default='', max_length=160)),
                ('bio', models.TextField(blank=True, default='')),
                ('city', models.CharField(max_length=120)),
                ('travel_radius_km', models.PositiveIntegerField(default=0)),
                ('base_price_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('occasions', models.JSONField(blank=True, default=list)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('typical_set_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('website_url', models.CharField(blank=True, default='', max_length=500)),
                ('instagram_url', models.CharField(blank=True, default='', max_length=500)),
                ('youtube_url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('rejected', 'Rejected'), ('live', 'Live'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_note', models.CharField(blank=True, default='', max_length=1000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_performers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performers', to='organizations.organization')),
            ],
            options={
                'db_table': 'performers_performer',
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performer_type', models.CharField(choices=[('band', 'Band'), ('singer', 'Singer'), ('dj', 'DJ'), ('instrumentalist', 'Instrumentalist'), ('anchor', 'Anchor / MC'), ('comedian', 'Stand-up comedian'), ('dance_crew', 'Dance crew'), ('magician', 'Magician'), ('other', 'Other')], max_length=20)),
                ('occasion', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('corporate', 'Corporate event'), ('college_fest', 'College fest'), ('private_party', 'Private party'), ('festival', 'Festival'), ('other', 'Other')], default='other', max_length=20)),
                ('city', models.CharField(max_length=120)),
                ('event_date', models.DateField()),
                ('budget_min_minor', models.PositiveIntegerField()),
                ('budget_max_minor', models.PositiveIntegerField()),
                ('guests', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open for quotes'), ('booked', 'Booked'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to=settings.AUTH_USER_MODEL)),
                ('booked_performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_requests', to='performers.performer')),
            ],
            options={
                'db_table': 'performers_booking_request',
            },
        ),
        migrations.CreateModel(
            name='PerformerMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='performers.performer')),
            ],
            options={
                'db_table': 'performers_media',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Awaiting the customer'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='performers.performer')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='performers.bookingrequest')),
            ],
            options={
                'db_table': 'performers_quote',
            },
        ),
        migrations.AddIndex(
            model_name='performer',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['status', 'city', '-created_at'], name='performer_status_city_idx'),
        ),
        migrations.AddIndex(
            model_name='performer',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['status', 'performer_type', '-created_at'], name='performer_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='performer',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', '-created_at'], name='performer_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='performer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='performer_search_gin'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['status', 'performer_type', 'city', '-created_at'], name='request_open_match_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['customer', '-created_at'], name='request_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingrequest',
            constraint=models.CheckConstraint(check=models.Q(('budget_max_minor__gte', models.F('budget_min_minor'))), name='request_budget_range_valid'),
        ),
        migrations.AddIndex(
            model_name='performermedia',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['performer', 'position'], name='performer_media_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['request', '-created_at'], name='quote_request_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['performer', '-created_at'], name='quote_performer_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('request', 'performer'), name='quote_one_per_performer_per_request'),
        ),
    ]
