# Generated by Django 5.0.14 on 2026-08-08 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0002_search_vector_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookingrequest',
            name='request_open_match_idx',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'Being handled'), ('closed_won', 'Booked'), ('closed_lost', 'Not booked'), ('cancelled', 'Withdrawn by the customer')], default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['status', 'created_at'], name='enquiry_queue_idx'),
        ),
    ]
