# Generated by Django 5.0.14 on 2026-08-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0003_remove_bookingrequest_request_open_match_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='kind',
            field=models.CharField(choices=[('marketplace', 'Marketplace brief'), ('enquiry', 'Operator-handled enquiry')], default='enquiry', max_length=16),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open for quotes'), ('booked', 'Booked'), ('expired', 'Expired'), ('new', 'New'), ('in_progress', 'Being handled'), ('closed_won', 'Booked'), ('closed_lost', 'Not booked'), ('cancelled', 'Withdrawn by the customer')], default='new', max_length=20),
        ),
    ]
