# Generated by Django 5.0.14 on 2026-08-10 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0004_bookingrequest_kind_alter_bookingrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['kind', 'status', 'performer_type', 'city', '-created_at'], name='request_open_match_idx'),
        ),
    ]
