"""The one same-origin rule, used by both places that need it.

Two things in this module hand a browser a destination somebody else typed:
the operator-authored banner `link_path`, and the `to` on the tracked redirect
in an announcement email. Both are open-redirect surfaces and both must apply
exactly the same rule, so the rule lives here once. Two copies of an
open-redirect check is how one of them drifts and the drifted one is the one
that ships in the email.

An open redirect on a link that arrives IN AN EMAIL FROM US is worse than one
anywhere else on the platform: the whole value of a phishing link is that the
domain in front of it is trusted, and a `curatix.example/...` URL that lands on
an attacker's login page is precisely the trust being spent.
"""

from __future__ import annotations

from core.errors import InvalidInputError

#: Prefixes that a browser resolves to a DIFFERENT origin even though the
#: string begins with a slash. `//host` is a protocol-relative URL; `/\host` is
#: treated as `//host` by every major browser; the percent-encoded forms are
#: rejected because some proxies normalise them before the browser sees them,
#: and a redirect target that means two things is one thing too many.
_OFF_ORIGIN_PREFIXES = ("//", "/\\", "/%2f", "/%5c")

#: A newline in a `Location` value is response-splitting. Django's own header
#: handling raises on these, but failing here gives a domain error the caller
#: can act on instead of a 500 from deep inside the response layer.
_HEADER_BREAKERS = "\r\n\t"


def is_site_path(value: str) -> bool:
    """True when `value` can only ever resolve to this site."""
    if not value.startswith("/"):
        return False
    if any(char in value for char in _HEADER_BREAKERS):
        return False
    lowered = value.lower()
    return not any(lowered.startswith(prefix) for prefix in _OFF_ORIGIN_PREFIXES)


def require_site_path(value: str, *, field: str) -> str:
    """Return `value` if it is a same-origin path, else raise.

    Raising rather than quietly falling back to `/` is the deliberate choice.
    Every link this module emits was generated by us, so a `to` that fails
    this check means either a tampered URL or a bug in our own campaign
    builder — and silently sending the reader to the homepage hides both from
    the operator who could fix them, while still teaching the reader that our
    links go somewhere other than where they said.
    """
    if not is_site_path(value):
        raise InvalidInputError(f"{field} must be a path on this site, e.g. /events.", field=field)
    return value
