# Generated by Django 5.0.14 on 2026-07-28 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('maintenance', 'Maintenance'), ('feature', 'New feature'), ('promotion', 'Promotion'), ('emergency', 'Emergency')], max_length=20)),
                ('placement', models.CharField(choices=[('home', 'Attendee homepage'), ('organizer', 'Organizer dashboard'), ('admin', 'Admin console'), ('all', 'Everywhere')], default='home', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, default='', max_length=400)),
                ('link_path', models.CharField(blank=True, default='', max_length=200)),
                ('link_label', models.CharField(blank=True, default='', max_length=40)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dismissible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements_announcement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['placement', 'starts_at'], name='ann_live_idx')],
            },
        ),
    ]
