# Generated by Django 5.0.14 on 2026-08-02 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements_subscriber',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_log_id', models.UUIDField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='announcements.announcement')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='announcements.subscriber')),
            ],
            options={
                'db_table': 'announcements_delivery',
            },
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(condition=models.Q(('unsubscribed_at__isnull', True)), fields=['created_at'], name='subscriber_active_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementdelivery',
            index=models.Index(condition=models.Q(('notification_log_id__isnull', True)), fields=['announcement', 'created_at'], name='anndelivery_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementdelivery',
            constraint=models.UniqueConstraint(fields=('announcement', 'subscriber'), name='announcement_delivery_unique'),
        ),
    ]
