# Generated by Django 5.0.14 on 2026-07-29 18:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('events', '0004_event_latitude_event_longitude_event_place_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_email', models.EmailField(blank=True, default='', max_length=254)),
                ('access_token_encrypted', models.TextField(blank=True, default='')),
                ('refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_scopes', models.JSONField(blank=True, default=list)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('needs_reconnect', 'Needs reconnect')], default='active', max_length=20)),
                ('status_detail', models.CharField(blank=True, default='', max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integrations_google_connection',
            },
        ),
        migrations.CreateModel(
            name='CalendarEventLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_event_id', models.CharField(max_length=255)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('html_link', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_links', to='booking.booking')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_links', to='events.event')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_links', to='integrations.googleconnection')),
            ],
            options={
                'db_table': 'integrations_calendar_event_link',
            },
        ),
        migrations.AddIndex(
            model_name='googleconnection',
            index=models.Index(fields=['status', 'access_token_expires_at'], name='gconn_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='calendareventlink',
            index=models.Index(fields=['event', 'deleted_at'], name='clink_event_deleted_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendareventlink',
            constraint=models.UniqueConstraint(fields=('connection', 'booking'), name='uniq_calendar_link_per_booking'),
        ),
    ]
