# Generated by Django 5.0.14 on 2026-07-24 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross', models.PositiveIntegerField(default=0)),
                ('platform_fee', models.PositiveIntegerField(default=0)),
                ('refunds', models.PositiveIntegerField(default=0)),
                ('net', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('releasable_at', models.DateTimeField(blank=True, null=True)),
                ('payout_at', models.DateTimeField(blank=True, null=True)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='events.event')),
            ],
            options={
                'db_table': 'settlements_settlement',
            },
        ),
        migrations.CreateModel(
            name='PayoutAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('adjustment', 'Adjustment')], max_length=16)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_attempts', to='settlements.settlement')),
            ],
            options={
                'db_table': 'settlements_payout_attempt',
            },
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['releasable_at'], name='settlement_release_scan_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutattempt',
            index=models.Index(fields=['settlement', 'created_at'], name='payoutattempt_settle_idx'),
        ),
    ]
