# Generated by Django 5.0.14 on 2026-08-10 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0004_bookingitem_phase_name'),
        ('events', '0010_event_rating_count_event_rating_sum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('body', models.TextField(blank=True, default='', max_length=2000)),
                ('verified_attendee', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('published', 'Published'), ('hidden', 'Hidden')], default='published', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='booking.booking')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_review',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event', 'status', '-created_at'], name='review_event_recent_idx'), models.Index(fields=['event', 'status', 'rating'], name='review_event_rating_idx'), models.Index(fields=['user', 'event'], name='review_user_event_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventreview',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='one_review_per_event_per_user'),
        ),
        migrations.AddConstraint(
            model_name='eventreview',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_within_scale'),
        ),
    ]
