import { describe, expect, it } from 'vitest';
import { urlBase64ToUint8Array } from './push';

/**
 * The VAPID key conversion.
 *
 * `applicationServerKey` wants raw bytes; the server sends unpadded base64url.
 * Passing the string straight through fails in Chrome with an error naming
 * neither the encoding nor the fix, and the failure only appears on a real
 * device — which is exactly the kind of thing to pin down in a unit test.
 */
describe('urlBase64ToUint8Array', () => {
  it('decodes a real VAPID public key to the 65 bytes a browser expects', () => {
    // Generated by `manage.py generate_vapid_keys`. An uncompressed P-256
    // point: 65 bytes, first byte 0x04.
    const key = 'BD1AW0Bd7gtLWXTPRytoabTsZeEIryQvrTbqWauotsuNadeL1yMeFbNOreTEb5nQRE0xuOFaNjaDbkP2ZpVdb5M';
    const bytes = urlBase64ToUint8Array(key);

    expect(bytes).toBeInstanceOf(Uint8Array);
    expect(bytes.length).toBe(65);
    expect(bytes[0]).toBe(0x04);
  });

  it('restores the padding base64url strips', () => {
    // "any carnal pleasure." — a value whose length is not a multiple of 4,
    // so it round-trips only if the padding is put back.
    const decoded = urlBase64ToUint8Array('YW55IGNhcm5hbCBwbGVhc3VyZS4');
    expect(new TextDecoder().decode(decoded)).toBe('any carnal pleasure.');
  });

  it('translates the url-safe alphabet, not just the padding', () => {
    // 0xFB 0xFF decodes from "+/8=" in standard base64 and "-_8" in base64url.
    // Getting this wrong yields plausible-looking bytes rather than an error.
    expect(Array.from(urlBase64ToUint8Array('-_8'))).toEqual([0xfb, 0xff]);
  });

  it('leaves an already-aligned value untouched', () => {
    expect(new TextDecoder().decode(urlBase64ToUint8Array('YW55IGNhcm5hbA'))).toBe('any carnal');
  });
});
