# Generated by Django 5.0.14 on 2026-08-07 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookingitem_phase_name'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='booking.booking')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_refund_request',
                'indexes': [models.Index(fields=['status', 'created_at'], name='refundreq_status_created_idx'), models.Index(fields=['booking', 'created_at'], name='refundreq_booking_created_idx'), models.Index(fields=['requested_by', 'created_at'], name='refundreq_user_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='refundrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('booking',), name='one_open_refund_request_per_booking'),
        ),
    ]
