# Generated by Django 5.0.14 on 2026-07-24 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('ticketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='reserved', max_length=20)),
                ('hold_expires_at', models.DateTimeField()),
                ('total_amount_minor', models.PositiveIntegerField()),
                ('platform_fee_minor', models.PositiveIntegerField()),
                ('payment_order_id', models.CharField(blank=True, default='', max_length=255)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_booking',
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_minor', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.booking')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='ticketing.tickettype')),
            ],
            options={
                'db_table': 'booking_booking_item',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_token', models.CharField(max_length=512, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('void', 'Void')], default='active', max_length=20)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('gate', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.booking')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticketing.tickettype')),
            ],
            options={
                'db_table': 'booking_ticket',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(condition=models.Q(('status', 'reserved')), fields=['hold_expires_at'], name='booking_expiry_sweep_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='booking_user_idempotency_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['booking', 'created_at'], name='ticket_booking_created_idx'),
        ),
    ]
