# Generated by Django 5.0.14 on 2026-08-03 17:24
"""Record WHICH sale phase priced each line of an order.

The line items are now written from the locked reserve decision rather than
from the pre-lock read of the tier, so `unit_price_minor` is exactly what the
booking was billed. This column records the label that price came under
("Early bird"), so the order can say why a line is below the tier's face price
instead of leaving the buyer to guess.

**NULL, not ''**, and the two mean different things. NULL is "billed at the
face price" — which is also the correct historical answer for every existing
row, since none of them was priced by a phase. A blank string would be a phase
whose name nobody wrote down.

No index: nothing filters or sorts by it. Every read reaches it through the
booking it belongs to.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_ticket_attendee_email_ticket_attendee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='phase_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
