# Generated by Django 5.1.15 on 2026-09-06 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_donation_amount_minor'),
        ('events', '0017_attendee_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='booking.booking')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='events.eventquestion')),
            ],
            options={
                'db_table': 'booking_answer',
                'indexes': [models.Index(fields=['question', 'created_at'], name='answer_question_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'question'), name='booking_answer_once_per_question')],
            },
        ),
    ]
