# Generated by Django 5.1.15 on 2026-09-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_attendee_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='group_min_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
