# Generated by Django 5.1.15 on 2026-09-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_bookingitem_group_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount_minor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
