# Generated by Django 5.1.15 on 2026-09-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_discount_amount_minor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_gateway',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
