# Generated by Django 5.0.14 on 2026-08-09 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0004_bookingitem_phase_name'),
        ('events', '0009_alter_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience', models.CharField(choices=[('organizer', 'The event organizer'), ('platform', 'Curatix support'), ('both', 'Both')], default='platform', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=16)),
                ('subject', models.CharField(max_length=140)),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_queries', to='events.event')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_queries', to='booking.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_query',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_staff_reply', models.BooleanField(default=False)),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_replies', to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='support.supportquery')),
            ],
            options={
                'db_table': 'support_reply',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='supportquery',
            index=models.Index(fields=['user', '-created_at'], name='support_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='supportquery',
            index=models.Index(fields=['status', '-created_at'], name='support_status_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='supportquery',
            index=models.Index(fields=['event', '-created_at'], name='support_event_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='supportreply',
            index=models.Index(fields=['query', 'created_at'], name='support_reply_thread_idx'),
        ),
    ]
