# Generated by Django 5.1.15 on 2026-09-06 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0007_bookingitem_group_min_quantity'),
        ('events', '0017_attendee_questionnaire'),
        ('organizations', '0002_organizationfollow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('kind', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off')], max_length=10)),
                ('value', models.PositiveIntegerField()),
                ('max_discount_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True)),
                ('max_per_user', models.PositiveIntegerField(default=1)),
                ('visible_at_checkout', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='organizations.organization')),
            ],
            options={
                'db_table': 'coupons_coupon',
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='booking.booking')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupons_redemption',
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['organization', 'code'], name='coupon_org_code_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['organization', '-created_at'], name='coupon_org_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='coupon_code_unique_per_org'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon'], name='redemption_coupon_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'user'], name='redemption_coupon_user_idx'),
        ),
    ]
