# Generated by Django 5.1.15 on 2026-09-12 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EphemeralToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=40)),
                ('token', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_ephemeral_token',
                'indexes': [models.Index(fields=['expires_at'], name='ephemeral_token_expiry')],
                'constraints': [models.UniqueConstraint(fields=('purpose', 'token'), name='ephemeral_token_unique')],
            },
        ),
    ]
