# Generated by Django 5.0.14 on 2026-08-02 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='organizations.organization')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='organization_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations_organization_follow',
                'indexes': [models.Index(fields=['organization', 'notify', 'user'], name='org_follow_org_notify_idx'), models.Index(fields=['user', '-created_at'], name='org_follow_user_recent_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='organizationfollow',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='org_follow_user_org_uniq'),
        ),
    ]
